services:
  bisheng-rt:
    container_name: bisheng-rt
    image: dataelement/bisheng-rt:0.0.6.2
    shm_size: 10gb
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9002:9002"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              device_ids: ['0,1']  # 指定想映射给rt服务使用的宿主机上的GPU ID号，如想映射多个卡，可写为['0','1','2']
    environment:
      TZ: Asia/Shanghai
    command: ["./bin/rtserver", "f"]
    volumes:
      - /home/public/llm:/opt/bisheng-rt/models/model_repository  # 冒号前为宿主机上放置模型目录的路径，请根据实际环境修改；冒号后为映射到容器内的路径，请勿修改
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/v2"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: on-failure

  bisheng-unstructured:
    container_name: bisheng-unstructured
    image: dataelement/bisheng-unstructured:0.0.3.2
    ports:
      - "10001:10001"
    environment:
      rt_server: bisheng-rt:9001
      TZ: Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10001/health"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: on-failure
